this is test   Cloud.Service.AWS.Kinesis.Firehose.Delivery.Stream_1:
    type: Cloud.Service.AWS.Kinesis.Firehose.Delivery.Stream
    properties:
      arn:
      name:
      count:
      region:
      account:
      version_id:
      destination:
      destination_id:
      s3_configuration:
        - 
        prefix:
        role_arn:
        bucket_arn:
        buffer_size:
        kms_key_arn:
        buffer_interval:
        compression_format:
        cloudwatch_logging_options:
          - 
          enabled:
          log_group_name:
          log_stream_name:
      splunk_configuration:
        - 
        hec_token:
        hec_endpoint:
        retry_duration:
        s3_backup_mode:
        hec_endpoint_type:
        processing_configuration:
          - 
          enabled:
          processors:
            - 
            type:
            parameters:
              - 
              parameter_name:
              parameter_value:
        cloudwatch_logging_options:
          - 
          enabled:
          log_group_name:
          log_stream_name:
        hec_acknowledgment_timeout:
      redshift_configuration:
        - 
        password:
        role_arn:
        username:
        copy_options:
        retry_duration:
        s3_backup_mode:
        cluster_jdbcurl:
        data_table_name:
        data_table_columns:
        s3_backup_configuration:
          - 
          prefix:
          role_arn:
          bucket_arn:
          buffer_size:
          kms_key_arn:
          buffer_interval:
          compression_format:
          cloudwatch_logging_options:
            - 
            enabled:
            log_group_name:
            log_stream_name:
        processing_configuration:
          - 
          enabled:
          processors:
            - 
            type:
            parameters:
              - 
              parameter_name:
              parameter_value:
        cloudwatch_logging_options:
          - 
          enabled:
          log_group_name:
          log_stream_name:
      extended_s3_configuration:
        - 
        prefix:
        role_arn:
        bucket_arn:
        buffer_size:
        kms_key_arn:
        s3_backup_mode:
        buffer_interval:
        compression_format:
        s3_backup_configuration:
          - 
          prefix:
          role_arn:
          bucket_arn:
          buffer_size:
          kms_key_arn:
          buffer_interval:
          compression_format:
          cloudwatch_logging_options:
            - 
            enabled:
            log_group_name:
            log_stream_name:
        processing_configuration:
          - 
          enabled:
          processors:
            - 
            type:
            parameters:
              - 
              parameter_name:
              parameter_value:
        cloudwatch_logging_options:
          - 
          enabled:
          log_group_name:
          log_stream_name:
        data_format_conversion_configuration:
          - 
          enabled:
          schema_configuration:
            - 
            region:
            role_arn:
            catalog_id:
            table_name:
            version_id:
            database_name:
          input_format_configuration:
            - 
            deserializer:
              - 
              hive_json_ser_de:
                - 
                timestamp_formats:
                  - 
                  string:
              open_x_json_ser_de:
                - 
                case_insensitive:
                column_to_json_key_mappings:
                convert_dots_in_json_keys_to_underscores:
          output_format_configuration:
            - 
            serializer:
              - 
              orc_ser_de:
                - 
                compression:
                enable_padding:
                format_version:
                block_size_bytes:
                row_index_stride:
                padding_tolerance:
                stripe_size_bytes:
                bloom_filter_columns:
                  - 
                  string:
                dictionary_key_threshold:
                bloom_filter_false_positive_probability:
              parquet_ser_de:
                - 
                compression:
                writer_version:
                page_size_bytes:
                block_size_bytes:
                max_padding_bytes:
                enable_dictionary_compression:
      elasticsearch_configuration:
        - 
        role_arn:
        type_name:
        domain_arn:
        index_name:
        buffering_size:
        retry_duration:
        s3_backup_mode:
        buffering_interval:
        index_rotation_period:
        processing_configuration:
          - 
          enabled:
          processors:
            - 
            type:
            parameters:
              - 
              parameter_name:
              parameter_value:
        cloudwatch_logging_options:
          - 
          enabled:
          log_group_name:
          log_stream_name:
      kinesis_source_configuration:
        - 
        role_arn:
        kinesis_stream_arn:
      id:
  #TYPE 'OPTIONAL' TO FIND OPTIONAL PROPERTIES FOR YOUR RESOURCE.
  
  