---
- hosts: localhost
  vars_prompt:
  - name: filesize
    prompt: "Enter the file size in megabytes"
  tasks:
  - name: check if file size is valid
    assert:
      that:
      - filesize <= 100
      - filesize >= 1
    fail_msg: "filesize must be between o and 100 megabytes"
    success_msg: "filesize is within the valid range"
  - name: creatre a file
    command: dd if=/dev/zero of=/bigfile bs=1 count={{ filesize }}