---
- name: simple block example
  hosts: all
  tasks:
  - name: settingup httpd
    block:
    - name: installing http
      yum:
        name: httpd
        state: present
    - name: restart httpd service
      service:
        name: httpd
        state: started
      when: ansible_os_family == "RedHat"
