---
- name: showing map
  hosts: all
  gather_facts: no
  ignore_errors: true
  vars:
    basedir: /var/www/html
  tasks:
  - name: install httpd
    apt:
      name: apache2
      state: latest
  - name: showing files in basedir
    find: 
      paths: "{{ basedir }}"
      recurse: yes
    register: basedir_files
  - name: showing current variable contents to understand why we need map
    debug: 
      var: basedir_files
  - name: showing files based on map attribures with list
    set_fact: 
      webfileslist: "{{ basedir_files['files'] | map(attribute='path') | list}}"
  - debug:
      var: webfileslist
  - name: now that we know that the list filter is mandatory, show relative file name
    set_fact:
      webfilesrelative: "{{ webfileslist | map('relpath', basedir) | list }}"
  - debug:
      var: webfilesrelative
  - name: collect mtime value for index file
    set_fact:
      mtime: "{{basedir_files['files'] | map(attribute='mtime') | list }}"
  - debug: 
      var: mtime