---
- name: showing handlers
  hosts: host1
  tasks:
  - name: install web server
    yum:
      name: httpd
      state: present
  - name: copy a file
    copy:
      src: /tmp/index.html
      dest: /var/www/html/index.html
    notify:
    - restart_web
  handlers:
  - name: restart_web
    service: 
      name: httpd
      state: restarted
      enabled: yes
