---
- name: idempotent command
  hosts: localhost
  ignore_errors: yes
  tasks:
  - command: useradd joan
    register: added_user
  - name: rc 9 is OK
    assert:
      that:
        - added_user.rc == 9 
      success_msg: "{{ added_user.user }} already exists - idempotent test"
  - debug:
      var: continuing here
  