---
- name: first task
  hosts: localhost
  tasks:
  - debug: msg="this is first message"
  - debug: msg="this is second message"
  tag: first
- name: second task
  hosts: localhost
  tasks:
  - debug: msg="this is third message"
  - debug: msg="this is fourth message"
  tag: second
